[tool.poetry]
name = "otree-realeffort"
version = "0.1.0"
description = ""
authors = ["Ryota"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.2.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
